const canvas=document.querySelector('#map'),ctx=canvas.getContext('2d');
const resetButton=document.querySelector('#reset'),position=document.querySelector('#position'),strategySelect=document.querySelector('#strategy'),stats=document.querySelector('#stats'),description=document.querySelector('#description'),problems=document.querySelector('#problems'),tracersToggle=document.querySelector('#tracers'),tracerStats=document.querySelector('#tracer-stats'),analysisStats=document.querySelector('#analysis-stats'),weightsSelect=document.querySelector('#weights'),weightRow=document.querySelector('#weight-row');
const TILE=200,portNames={T:'T0',L:'L0',R:'R0',B:'B0',l:'L1',r:'R1'},portPos={T:[100,0],L:[0,50],R:[200,150],B:[100,200],l:[0,150],r:[200,50]},portColor={T:'#7048b8',L:'#218065',R:'#c55f24',B:'#7d5a35',l:'#2676ad',r:'#bd3d66'};
const descriptions={current:'The production generator. Tiles are selected independently, so neighboring ports often disagree.','three-lane':'Every tile exposes all three current inputs and outputs: T0 → B0, L0 → L1, and R0 → R1.',southeast:'Every tile exposes T0 + L0 inputs and B0 + R1 outputs, paired straight through.',southwest:'Every tile exposes T0 + R0 inputs and B0 + L1 outputs, paired straight through.',mixed:'Every tile has the southeast signature. Straight and switched internal pairings vary deterministically.',mixed3:'Every tile exposes all three inputs and outputs. One of the six bijective route permutations is selected deterministically.',edges:'Connections are generated on shared edges first. Each tile derives its ports from those edges; isolated and 3-way tiles may occur.'};
const permutations=[['B','l','r'],['B','r','l'],['l','B','r'],['l','r','B'],['r','B','l'],['r','l','B']];
const weightPresets={equal:[1,1,1,1,1,1],turn:[1,2,2,2,2,1],straight:[4,1,1,1,1,4],down:[3,2,2,2,2,3],mixed:[3,1,2,2,1,3]};
function currentWeights(){return weightPresets[weightsSelect.value]||weightPresets.equal;}
function weightedPermutation(row,col){const weights=currentWeights(),total=weights.reduce((a,b)=>a+b,0);let value=hash(row,col,191)*total;for(let i=0;i<weights.length;i++){value-=weights[i];if(value<0)return permutations[i];}return permutations[5];}
let mapData,zoom=.5,viewX=-innerWidth/zoom/2,viewY=-innerHeight/zoom/3,drag=null,pinches=new Map(),pinch=null,tracerTime=0,lastFrame=performance.now(),tracerStates=[];
fetch('./map-data.json?v=0.1').then(response=>response.json()).then(data=>{mapData=data;draw();});
function hash(row,col,salt=0){let n=Math.imul(row^0x9e3779b9,0x85ebca6b)^Math.imul(col^salt,0xc2b2ae35);n^=n>>>16;n=Math.imul(n,0x7feb352d);n^=n>>>15;return(n>>>0)/4294967296;}
function currentAt(row,col){if(row<mapData.minRow||row>mapData.maxRow||col<mapData.minCol||col>mapData.maxCol)return null;return mapData.codes[mapData.rows[row-mapData.minRow][col-mapData.minCol]];}
function routeAt(row,col){switch(strategySelect.value){case'current':return currentAt(row,col)||'T>B';case'three-lane':return'TB,Ll,Rr';case'southeast':return'TB,Lr';case'southwest':return'TB,Rl';case'mixed':return hash(row,col,91)<.5?'TB,Lr':'Tr,LB';case'mixed3':{const p=weightedPermutation(row,col);return`T${p[0]},L${p[1]},R${p[2]}`;}case'edges':return edgeRoute(row,col);}}
function verticalEdge(row,col){return hash(row,col,311)<.72;} // between row and row+1
function horizontalEdge(row,col){return hash(row,col,733)<.62;} // between col and col+1, left-to-right
function edgeRoute(row,col){const entries=[],exits=[];if(verticalEdge(row-1,col))entries.push('T');if(horizontalEdge(row,col-1))entries.push('L');if(verticalEdge(row,col))exits.push('B');if(horizontalEdge(row,col))exits.push('r');return entries.join('')+'>'+exits.join('');}
function pairs(route){if(!route)return[];if(route.includes(','))return route.split(',').filter(Boolean).map(x=>[x[0],x[1]]);const[e='',x='']=route.split('>');return[...e].slice(0,x.length).map((p,i)=>[p,x[i]]);}
function signature(route){if(!route)return{ins:new Set(),outs:new Set(),inCount:0,outCount:0};if(!route.includes(',')){const[e='',x='']=route.split('>'),ins=new Set(e),outs=new Set(x);return{ins,outs,inCount:ins.size,outCount:outs.size};}const ps=pairs(route),ins=new Set(ps.map(x=>x[0])),outs=new Set(ps.map(x=>x[1]));return{ins,outs,inCount:ins.size,outCount:outs.size};}
function hasInput(row,col,p){return signature(routeAt(row,col)).ins.has(p);}function hasOutput(row,col,p){return signature(routeAt(row,col)).outs.has(p);}
function errorsAt(row,col){const e=[];if(hasOutput(row,col,'B')!==hasInput(row+1,col,'T'))e.push('B');if(hasOutput(row,col,'r')!==hasInput(row,col+1,'L'))e.push('r');if(hasInput(row,col,'T')!==hasOutput(row-1,col,'B'))e.push('T');if(hasInput(row,col,'L')!==hasOutput(row,col-1,'r'))e.push('L');return e;}
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);draw();}
function setZoom(next,cx=innerWidth/2,cy=innerHeight/2){next=Math.max(.08,Math.min(3,next));const wx=viewX+cx/zoom,wy=viewY+cy/zoom;zoom=next;viewX=wx-cx/zoom;viewY=wy-cy/zoom;resetButton.textContent=`${zoom.toFixed(2).replace(/0$/,'')}×`;draw();}
function reset(){zoom=.5;viewX=-innerWidth/zoom/2;viewY=-innerHeight/zoom/3;setZoom(.5);}
function curve(a,b,index){const[ax,ay]=portPos[a],[bx,by]=portPos[b],bend=(index-.5)*25;ctx.beginPath();ctx.moveTo(ax,ay);ctx.bezierCurveTo(ax+(bx-ax)*.35+bend,ay+(by-ay)*.12,bx-(bx-ax)*.2+bend,by-(by-ay)*.32,bx,by);ctx.strokeStyle=portColor[a];ctx.lineWidth=7;ctx.globalAlpha=.72;ctx.stroke();ctx.globalAlpha=1;const t=.91,x=(1-t)**3*ax+3*(1-t)**2*t*(ax+(bx-ax)*.35+bend)+3*(1-t)*t*t*(bx-(bx-ax)*.2+bend)+t**3*bx,y=(1-t)**3*ay+3*(1-t)**2*t*(ay+(by-ay)*.12)+3*(1-t)*t*t*(by-(by-ay)*.32)+t**3*by,angle=Math.atan2(by-y,bx-x);ctx.fillStyle=portColor[b];ctx.beginPath();ctx.moveTo(bx,by);ctx.lineTo(bx-Math.cos(angle-.5)*15,by-Math.sin(angle-.5)*15);ctx.lineTo(bx-Math.cos(angle+.5)*15,by-Math.sin(angle+.5)*15);ctx.closePath();ctx.fill();}
function drawProblemEdges(row,col,errors){if(!problems.checked||!errors.length)return;ctx.strokeStyle='#d71f34';ctx.lineWidth=7/zoom;ctx.globalAlpha=.8;for(const p of errors){ctx.beginPath();if(p==='T'){ctx.moveTo(0,0);ctx.lineTo(200,0)}else if(p==='B'){ctx.moveTo(0,200);ctx.lineTo(200,200)}else if(p==='L'){ctx.moveTo(0,0);ctx.lineTo(0,200)}else{ctx.moveTo(200,0);ctx.lineTo(200,200)}ctx.stroke()}ctx.globalAlpha=1;}
function drawTile(row,col){const route=routeAt(row,col),ps=pairs(route),sig=signature(route),errors=errorsAt(row,col);ctx.save();ctx.translate(col*TILE,row*TILE);ctx.fillStyle=(row+col)%2?'rgba(255,250,236,.48)':'rgba(255,255,255,.27)';ctx.fillRect(0,0,TILE,TILE);ctx.strokeStyle='rgba(73,58,37,.22)';ctx.lineWidth=1/zoom;ctx.strokeRect(0,0,TILE,TILE);ps.forEach((v,i)=>curve(v[0],v[1],i));const used=new Set([...sig.ins,...sig.outs]);for(const p of used){const[x,y]=portPos[p];ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.fillStyle=portColor[p];ctx.fill();if(zoom>.38){ctx.fillStyle='#302c26';ctx.font='700 10px ui-monospace';ctx.textAlign=x===0?'left':x===200?'right':'center';ctx.fillText(portNames[p],x+(x===0?12:x===200?-12:0),y+(y===0?18:y===200?-12:4));}}drawProblemEdges(row,col,errors);if(zoom>.55){ctx.fillStyle='rgba(48,44,38,.58)';ctx.font='10px ui-monospace';ctx.textAlign='left';ctx.fillText(`${row},${col}`,7,16);ctx.fillText(`${sig.inCount} in / ${sig.outCount} out`,7,188);}ctx.restore();return{sig,errors};}
function updateStats(minRow,maxRow,minCol,maxCol){let tiles=0,mismatch=0,balanced=0,splits=0,merges=0,inTotal=0,outTotal=0;const signatures=new Map();for(let r=minRow;r<=maxRow;r++)for(let c=minCol;c<=maxCol;c++){tiles++;const sig=signature(routeAt(r,c)),err=errorsAt(r,c);mismatch+=err.filter(x=>x==='B'||x==='r').length;inTotal+=sig.inCount;outTotal+=sig.outCount;if(sig.inCount===sig.outCount)balanced++;if(sig.outCount>sig.inCount)splits++;if(sig.inCount>sig.outCount)merges++;const k=`${sig.inCount}→${sig.outCount}`;signatures.set(k,(signatures.get(k)||0)+1);}stats.innerHTML=`<span>Edges mismatched <b>${mismatch}</b></span><span>Balanced tiles <b>${Math.round(balanced/tiles*100)}%</b></span><span>Splits <b>${splits}</b></span><span>Merges <b>${merges}</b></span><span>Mean inputs <b>${(inTotal/tiles).toFixed(2)}</b></span><span>Mean outputs <b>${(outTotal/tiles).toFixed(2)}</b></span><span>Signatures <b>${[...signatures].map(x=>x.join(':')).join(' ')}</b></span>`;}
function nextTracer(row,col,input){const route=pairs(routeAt(row,col)),pair=route.find(x=>x[0]===input);if(!pair)return null;const out=pair[1];if(out==='B')return[row+1,col,'T'];if(out==='l')return[row,col-1,'R'];if(out==='r')return[row,col+1,'L'];return null;}
function initTracers(){tracerStates=[];for(let i=0;i<48;i++){const row=Math.floor((hash(i,17,1)-.5)*30),col=Math.floor((hash(i,29,2)-.5)*30),inputs=['T','L','R'],input=inputs[Math.floor(hash(i,41,3)*3)];tracerStates.push({row,col,input,next:null,progress:hash(i,53,4),startRow:row,startCol:col,visited:new Set([`${row},${col},${input}`]),tiles:new Set([`${row},${col}`]),steps:0,loop:0,dead:false});}}
function stepTracer(t){if(t.dead)return;while(t.progress>=1){t.progress-=1;const key=`${t.row},${t.col},${t.input}`,next=nextTracer(t.row,t.col,t.input);if(!next){t.dead=true;return;}t.row=next[0];t.col=next[1];t.input=next[2];t.steps++;t.tiles.add(`${t.row},${t.col}`);const nk=`${t.row},${t.col},${t.input}`;if(t.visited.has(nk)&&!t.loop)t.loop=t.steps;t.visited.add(nk);if(t.steps>500){t.dead=true;return;}}t.next=nextTracer(t.row,t.col,t.input);}
function tracerPoint(t){const route=pairs(routeAt(t.row,t.col)),pair=route.find(x=>x[0]===t.input);if(!pair)return[t.col*TILE+100,t.row*TILE+100];const a=portPos[pair[0]],b=portPos[pair[1]],u=Math.max(0,Math.min(1,t.progress)),smooth=u*u*(3-2*u);return[t.col*TILE+a[0]+(b[0]-a[0])*smooth,t.row*TILE+a[1]+(b[1]-a[1])*smooth];}
function drawTracers(){if(!tracersToggle.checked)return;ctx.save();for(let i=0;i<tracerStates.length;i++){const t=tracerStates[i],p=tracerPoint(t);ctx.beginPath();ctx.arc(p[0],p[1],7/Math.sqrt(zoom),0,Math.PI*2);ctx.fillStyle=`hsl(${(i*47)%360} 78% 43%)`;ctx.globalAlpha=.9;ctx.fill();ctx.strokeStyle='rgba(255,255,255,.85)';ctx.lineWidth=2/zoom;ctx.stroke();}ctx.restore();}
function updateTracerStats(){const live=tracerStates.filter(t=>!t.dead),looped=tracerStates.filter(t=>t.loop),unique=new Set();tracerStates.forEach(t=>t.tiles.forEach(x=>unique.add(x)));const avgLoop=looped.length?looped.reduce((s,t)=>s+t.loop,0)/looped.length:0,driftX=tracerStates.reduce((s,t)=>s+t.col-t.startCol,0)/tracerStates.length,driftY=tracerStates.reduce((s,t)=>s+t.row-t.startRow,0)/tracerStates.length;tracerStats.textContent=`Animated: ${live.length} live · ${looped.length} looped · ${unique.size} unique tiles · avg loop ${avgLoop.toFixed(1)} · drift (${driftX.toFixed(1)}, ${driftY.toFixed(1)})`;}
function analyzeRoutes(){const count=300,maxSteps=2500,loopLengths=[],unique=new Set();let shortLoops=0,driftX=0,driftY=0,deadEnds=0;for(let i=0;i<count;i++){let row=Math.floor((hash(i,117,1)-.5)*80),col=Math.floor((hash(i,129,2)-.5)*80),input=['T','L','R'][Math.floor(hash(i,141,3)*3)],startRow=row,startCol=col;const seen=new Map();for(let step=0;step<maxSteps;step++){const key=`${row},${col},${input}`;unique.add(`${row},${col}`);if(seen.has(key)){const length=step-seen.get(key);loopLengths.push(length);if(length<=12)shortLoops++;break;}seen.set(key,step);const next=nextTracer(row,col,input);if(!next){deadEnds++;break;}[row,col,input]=next;}driftX+=col-startCol;driftY+=row-startRow;}loopLengths.sort((a,b)=>a-b);const median=loopLengths.length?loopLengths[Math.floor(loopLengths.length/2)]:0;analysisStats.textContent=`Long run: ${(loopLengths.length/count*100).toFixed(1)}% looped · ${(shortLoops/count*100).toFixed(1)}% short loops · median loop ${median} · ${unique.size} tiles covered · drift (${(driftX/count).toFixed(0)}, ${(driftY/count).toFixed(0)}) · ${deadEnds} dead ends`;}
function draw(){if(!mapData)return;const dpr=canvas.width/innerWidth;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#f2e7c9';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.save();ctx.scale(zoom,zoom);ctx.translate(-viewX,-viewY);const minCol=Math.floor(viewX/TILE)-1,maxCol=Math.ceil((viewX+innerWidth/zoom)/TILE)+1,minRow=Math.floor(viewY/TILE)-1,maxRow=Math.ceil((viewY+innerHeight/zoom)/TILE)+1;for(let r=minRow;r<=maxRow;r++)for(let c=minCol;c<=maxCol;c++)drawTile(r,c);drawTracers();ctx.restore();updateStats(minRow,maxRow,minCol,maxCol);updateTracerStats();description.textContent=descriptions[strategySelect.value];weightRow.hidden=strategySelect.value!=='mixed3';position.textContent=`row ${Math.floor((viewY+innerHeight/zoom/2)/TILE)} · col ${Math.floor((viewX+innerWidth/zoom/2)/TILE)} · ${zoom.toFixed(2)}×`;}
function animate(now){const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;if(mapData&&tracersToggle.checked){tracerStates.forEach(t=>{t.progress+=dt*.72;stepTracer(t)});draw();}requestAnimationFrame(animate);}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pinches.set(e.pointerId,[e.clientX,e.clientY]);if(pinches.size===1)drag=[e.clientX,e.clientY];else if(pinches.size===2){const p=[...pinches.values()],dx=p[0][0]-p[1][0],dy=p[0][1]-p[1][1];pinch={distance:Math.hypot(dx,dy),zoom};drag=null;}});canvas.addEventListener('pointermove',e=>{if(!pinches.has(e.pointerId))return;pinches.set(e.pointerId,[e.clientX,e.clientY]);if(pinches.size===2&&pinch){const p=[...pinches.values()],dx=p[0][0]-p[1][0],dy=p[0][1]-p[1][1],cx=(p[0][0]+p[1][0])/2,cy=(p[0][1]+p[1][1])/2;setZoom(pinch.zoom*Math.hypot(dx,dy)/pinch.distance,cx,cy);}else if(drag){viewX-=(e.clientX-drag[0])/zoom;viewY-=(e.clientY-drag[1])/zoom;drag=[e.clientX,e.clientY];draw();}});function end(e){pinches.delete(e.pointerId);pinch=null;drag=pinches.size===1?[...pinches.values()][0]:null}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.001),e.clientX,e.clientY)},{passive:false});
document.querySelector('#out').onclick=()=>setZoom(zoom/1.25);document.querySelector('#in').onclick=()=>setZoom(zoom*1.25);resetButton.onclick=reset;strategySelect.onchange=()=>{initTracers();analyzeRoutes();draw()};weightsSelect.onchange=()=>{initTracers();analyzeRoutes();draw()};problems.onchange=draw;tracersToggle.onchange=()=>{if(tracersToggle.checked)initTracers();draw()};addEventListener('keydown',e=>{if(e.key==='+'||e.key==='=')setZoom(zoom*1.25);else if(e.key==='-'||e.key==='_')setZoom(zoom/1.25);else if(e.key==='0')reset();else{const d=80/zoom;if(e.key==='ArrowLeft')viewX-=d;else if(e.key==='ArrowRight')viewX+=d;else if(e.key==='ArrowUp')viewY-=d;else if(e.key==='ArrowDown')viewY+=d;else return;draw()}e.preventDefault()});addEventListener('resize',resize);initTracers();analyzeRoutes();resize();requestAnimationFrame(animate);
